import React from "react";
import ReactDOM from "react-dom";
// // import { CounterApp } from "./components/01-useState/counterApp";
// // import SimpleForm from "./components/02-useEffect/SimpleForm";
// // import FormWithCustomHook from "./components/02-useEffect/FormWithCustomHook";
// // import { MultipleCustomHooks } from "./components/03-example/MultipleCustomHooks";
// // import { CounterWithCustomHook } from "./components/01-useState/CounterWithCustomHook";
// // import { HookApp } from "./hookApp";

// // import { FocusScreem } from "./components/04-useRef/FocusScreem";
// // import { RealExampleRef } from "./components/04-useRef/RealExampleRef";
// // import { Layout } from "./components/05-useLayoutEffact/LayoutEffect";
 //import "./index.css";
// //import { Memorize } from "./components/06-memos/memorize";
// //import { MemoHook } from "./components/06-memos/Memohook";
// //import { CallbackHook } from "./components/06-memos/CallbackHook";
//import { Padre } from "./components/07-tarea-memo/Padre";
//import { TodoApp } from "./components/08-useReducer/TodoApp";
import { MainApp } from "./components/09-useContext/MainApp";
ReactDOM.render(<MainApp />, document.getElementById("root"));
